language: python

python: 2.7

sudo: false
cache:
  directories: [$HOME/.cache/pip]

install: pip install -q -r --upgrade requirements.txt

script: sphinx-build -nW -c _build/ -b html -d _build/doctrees . _build/html

branches:
  except:
    - github-comments
